### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by Aurik-Datta** [sanishkr/react-floating-balloons#3]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-floating-balloons@3.0.1
npm ERR! node_modules/react-floating-balloons
npm ERR!   react-floating-balloons@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Was wondering if react 18 would ever be supported or if the project has been archived

**Comment by sanishkr** [comment]
Please share a sandbox to reproduce this issue. That's helpful.

I create a simple one [here](https://stackblitz.com/edit/stackblitz-starters-w4xjhb?file=src%2FApp.js) and seems to be working fine for me with latest react version.

Feel free to re-open it if you can provide details.
PRs are also welcome and appreciated.
