### ISSUE TITLE
Balloons are not floating to the top

### ISSUE THREAD

**Issue by buhln** [sanishkr/react-floating-balloons#4]
I added the ReactFloatingBalloons component to the mainsite of my application and the balloons start floating but were removed and restartet around the half of screenheight. Looks like that the component is rerendered.

```
<ReactFloatingBalloons
  count={3}
  msgText=""
/>
```

Any ideas how to investigate this issue further?

Thanks!

**Comment by sanishkr** [comment]
You need to set `hangOnTop` to `true` and `loop` to `false` for that. Please read documentation more carefully to understand.
